language: java
jdk: oraclejdk8
script: ./test-all-versions.sh
install: mvn install -DskipTests=true -Dgpg.skip=true
after_success: ./push-javadoc-to-gh-pages.sh
env:
    global:
        secure: "FWHVzDfKWfak06QtiuhImMt900A8Dg5oKQaRf7JSTZohmbKZsiYatWcVUUn+uEwXZ/fopaoMR0vYFfCiVacFF7WpnrsP5D3wnvNme2zGdoBdTZSbDu8l3zDfCdCk0S51zWsO5iM7rt799j7mJA7PDu1GvhkNRxZLrY5t0FPn3F+S9DVjUxequau7kWeiMNPucN/wKbC44ul98xQPwXW5IKtdFbchyI0LrftN/wrSzltGQd4Emhud0uYNKGexpE1tS9iuf75wtbjE3v8/xJtMidn2uoPXzeye45dFIEEL7TzeZTIDA2ia2S+Q165XVAv49GkK9lBNx0p1O18fETTfIiWmS4+mpIPsGqPPbIjNIa2ebGgVs3DfSaT7Hs10UcasGjZTGwVI43eRr94ctjW0/yz1E5JDhHCImo0vdQWgV5BPe1CD8R9qLSehI+BoM1lIJimrAevmCvWFT8zT46jR+WqjnF6RtXfijmTLIAHRIV0pa6A/RpHGMG6aXRle+zVjlCc7n548IiWC4k0JcW9WGhNEC/bnxvyTTmTektCQ5EoUtxq0In6JBy12QyRjY31tyu8SoqCLwlo1sSr/FWPVunI57GJAy2kL6zbVmk4Gpp7FRevjhUakZqWARd2z/T+nHHtYiusTBuzrn+l9Y/kr86xubPT7csoMxAVY9X9UZ4s="
